package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "guild-fields",
    srcs = ["guild-fields.html"],
    path = "/guild-fields",
    deps = [
        "//components/guild-field",
        "//components/guild-styles",
    ],
)
