package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "guild-series",
    srcs = ["guild-series.html"],
    path = "/guild-series",
    deps = [
        "//components/guild-chart",
        "//components/guild-styles",
    ],
)
