#-*-python-*-

package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "guild-run-select-page-header",
    srcs = [
        "guild-run-select-page-header.html",
    ],
    path = "/guild-run-select-page-header",
    deps = [
        "//components/guild-page-header",
        "//components/guild-run-select",
        "//components/guild-run-status",
    ],
)
