package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "ts_web_library")

ts_web_library(
    name = "guild-run-select-page-header",
    srcs = [
        "guild-run-select-page-header.html",
    ],
    path = "/guild-run-select-page-header",
    deps = [
        "//components/guild-page-header",
        "//components/guild-run-select",
        "//components/guild-run-status",
    ],
)
