package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "guild-icons",
    srcs = ["guild-icons.html"],
    path = "/guild-icons",
    deps = [
        "@org_polymer_iron_icons",
        "@org_pkaske_font_awesome_polymer_icons",
    ],
)
