package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "guild-expansion-panel",
    srcs = ["guild-expansion-panel.html"],
    path = "/guild-expansion-panel",
    deps = [
        "@org_polymer_iron_icons",
        "@org_polymer_iron_collapse",
        "@org_polymer_paper_icon_button",
    ],
)
