package(default_visibility = ["//visibility:public"])

java_library(
    name = "HtmlTreeBuilder2",
    srcs = [
        "HtmlTreeBuilder2.java",
        "HtmlTreeBuilderState2.java",
    ],
    deps = [
        "@org_jsoup",
    ],
)

