#-*-python-*-

package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "vz-keyval-table",
    srcs = ["vz-keyval-table.html"],
    path = "/vz-keyval-table",
    deps = [
        "//components/guild-styles",
    ],
)
