package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "ts_web_library")

ts_web_library(
    name = "vz-keyval-table",
    srcs = ["vz-keyval-table.html"],
    path = "/vz-keyval-table",
    deps = [
        "//components/guild-styles",
    ],
)
