package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "ts_web_library")

ts_web_library(
    name = "guild-styles",
    srcs = ["guild-styles.html"],
    path = "/guild-styles",
)
