package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "guild-page-header",
    srcs = ["guild-page-header.html"],
    path = "/guild-page-header",
    deps = [
        "@org_polymer_paper_tooltip",
    ],
)
