package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "ts_web_library")

ts_web_library(
    name = "guild-page-header",
    srcs = ["guild-page-header.html"],
    path = "/guild-page-header",
    deps = [
        "@org_polymer_paper_tooltip",
    ],
)
