package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "grid-xxl",
    srcs = [
        "bootstrap-grid-xxl.css",
    ],
    path = "/guild-bootstrap",
)
