package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "ts_web_library")

ts_web_library(
    name = "grid-xxl",
    srcs = [
        "bootstrap-grid-xxl.css",
    ],
    path = "/guild-bootstrap",
)
