package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "ts_web_library")

ts_web_library( name = "guild-component-panel", srcs =
    ["guild-component-panel.html"], path = "/guild-component-panel",
    deps = [ "//components/guild-expansion-panel",
    "@org_polymer_paper_material", ], )
