package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library( name = "guild-component-panel", srcs =
    ["guild-component-panel.html"], path = "/guild-component-panel",
    deps = [ "//components/guild-expansion-panel",
    "@org_polymer_paper_material", ], )
