package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "guild-component-options",
    srcs = ["guild-component-options.html"],
    path = "/guild-component-options",
    deps = [
        "@org_polymer_iron_icons",
        "@org_polymer_paper_icon_button",
        "@org_polymer_paper_menu_button",
    ],
)

web_library(
    name = "option-dropdown",
    srcs = ["option-dropdown.html"],
    path = "/guild-component-options",
    deps = [
        "@org_polymer_paper_button",
        "@org_polymer_paper_icon_button",
        "@org_polymer_paper_menu_button",
        "@org_polymer_paper_menu",
    ],
)

web_library(
    name = "option-element",
    srcs = ["option-element.html"],
    path = "/guild-component-options",
)
