package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "ts_web_library")

ts_web_library(
    name = "guild-component-options",
    srcs = ["guild-component-options.html"],
    path = "/guild-component-options",
    deps = [
        "@org_polymer_iron_icons",
        "@org_polymer_paper_icon_button",
        "@org_polymer_paper_menu_button",
    ],
)

ts_web_library(
    name = "option-dropdown",
    srcs = ["option-dropdown.html"],
    path = "/guild-component-options",
    deps = [
        "@org_polymer_paper_button",
        "@org_polymer_paper_icon_button",
        "@org_polymer_paper_menu_button",
        "@org_polymer_paper_menu",
    ],
)

ts_web_library(
    name = "option-element",
    srcs = ["option-element.html"],
    path = "/guild-component-options",
)
