package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "guild-smoothing-input",
    srcs = ["guild-smoothing-input.html"],
    path = "/guild-smoothing-input",
    deps = [
        "@org_polymer_paper_slider",
    ],
)
