package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "ts_web_library")

ts_web_library(
    name = "guild-smoothing-input",
    srcs = ["guild-smoothing-input.html"],
    path = "/guild-smoothing-input",
    deps = [
        "@org_polymer_paper_slider",
    ],
)
