package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "ts_web_library")

ts_web_library(
    name = "guild-filter-input",
    srcs = ["guild-filter-input.html"],
    path = "/guild-filter-input",
    deps = [
        "@org_polymer_iron_icon",
        "@org_polymer_iron_icons",
        "@org_polymer_paper_input",
    ],
)
