#-*-python-*-

package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "guild-filter-input",
    srcs = ["guild-filter-input.html"],
    path = "/guild-filter-input",
    deps = [
        "@org_polymer_iron_icon",
        "@org_polymer_iron_icons",
        "@org_polymer_paper_input",
    ],
)
