package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "ts_web_library")

ts_web_library(
    name = "guild-checkbox",
    srcs = ["guild-checkbox.html"],
    path = "/guild-checkbox",
    deps = [
        "@org_polymer_paper_checkbox",
    ],
)
