#!/usr/bin/env python

import argparse
import doctest
import os
import sys

import guild

ALL_TESTS = [
    "cmd-support",
    "db",
    "op-support",
    "opdir-meta",
    "project",
    "project-support",
    "project-util",
    "runs",
    "util",
    "view"
]

def main():
    p = argparse.ArgumentParser()
    p.add_argument("tests", nargs="*", help="tests to run")
    args = p.parse_args()
    tests = args.tests or ALL_TESTS
    errors = False
    for name in tests:
        success = test(name)
        errors = errors or not success
    if errors:
        sys.exit(1)

def test(name):
    sys.stdout.write(name + ":")
    failures, tests = guild.test.testfile(testfile_path(name))
    if not failures:
        sys.stdout.write(" " * (20 - len(name)))
        sys.stdout.write(" ok\n")
    return failures == 0

def testfile_path(name):
    return os.path.join("../tests", name + ".rst")

if __name__ == "__main__":
    main()
