package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "ts_web_library")

ts_web_library(
    name = "guild-project",
    srcs = [
        "guild-project.html",
        "project.ts",
    ],
    path = "/guild-project",
)
